#!/usr/bin/env python3
"""Render three real paired runs by physical motor-command replay.

No frame is generated by teleporting the robot to a saved joint state. Initial
ControlTask construction is the only reset; every later state uses advance().
"""
import argparse
from contextlib import ExitStack
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont
import pybullet as p

from panda_posture.task import ControlTask


PANE_WIDTH, PANE_HEIGHT = 512, 480
HEADER_HEIGHT, FOOTER_HEIGHT = 100, 78
FPS = 30
REPLAY_ATOL = 1e-7


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def font(size):
    try:
        return ImageFont.truetype('DejaVuSans.ttf', size)
    except OSError:
        return ImageFont.load_default(size=size)


class ReplayPane:
    def __init__(self, directory, label, stack):
        self.directory, self.label = directory, label
        self.cfg = json.loads((directory / 'config.json').read_text())
        self.source_summary = json.loads((directory / 'summary.json').read_text())
        with np.load(directory / 'trajectory.npz', allow_pickle=False) as data:
            self.commands = data['command'].copy()
            self.q_saved = data['q'].copy()
            self.time_saved = data['time'].copy()
        if self.commands.ndim != 2 or self.commands.shape[1] != 7:
            raise ValueError(f'{label}: invalid motor command array')
        if self.q_saved.shape != (len(self.commands) + 1, 7):
            raise ValueError(f'{label}: expected one more q state than commands')
        if not np.all(np.isfinite(self.commands)) or not np.all(np.isfinite(self.q_saved)):
            raise ValueError(f'{label}: cannot render nonfinite replay')
        if len(self.commands) != self.source_summary['physics_steps']:
            raise ValueError(f'{label}: source step count disagrees with trajectory')
        self.task = stack.enter_context(ControlTask(self.cfg))
        # Split the original action-repeat groups to sample exact video times.
        # The complete per-physics-step commands and dt remain identical.
        self.task.action_repeat = 1
        self.max_q_difference = 0.0
        self.frozen = None
        self.failure_time = None
        self.failure_reasons = []
        self.view = p.computeViewMatrixFromYawPitchRoll(
            cameraTargetPosition=[0.25, 0, 0.42], distance=1.25,
            yaw=(150 if directory.name == 'study-4490-0017' else 48), pitch=-24, roll=0, upAxisIndex=2)
        self.projection = p.computeProjectionMatrixFOV(
            fov=50, aspect=PANE_WIDTH/PANE_HEIGHT, nearVal=0.05, farVal=4)
        self._check_state()
        self._freeze_if_failed()

    def _check_state(self):
        index = self.task.steps
        difference = float(np.max(np.abs(self.task.state['q'] - self.q_saved[index])))
        self.max_q_difference = max(self.max_q_difference, difference)
        if difference > REPLAY_ATOL:
            raise ValueError(f'{self.label}: physical replay diverged at step {index}: {difference} rad')
        if abs(self.task.state['t'] - self.time_saved[index]) > 1e-10:
            raise ValueError(f'{self.label}: saved/reference clocks disagree')

    def _freeze_if_failed(self):
        if self.frozen is None and self.task.monitor.reasons:
            self.failure_time = self.task.state['t']
            self.failure_reasons = sorted(self.task.monitor.reasons)
            self.frozen = (self._render_scene(), dict(self.task.state))

    def advance_to(self, display_time):
        target_steps = min(len(self.commands), round(display_time/self.cfg['dt']))
        while self.task.steps < target_steps:
            if self.task.done:
                raise ValueError(f'{self.label}: physical replay terminated before source record')
            self.task.advance(np.zeros(7), replay_commands=self.commands)
            self._check_state()
            self._freeze_if_failed()

    def _pixel(self, xyz):
        view = np.asarray(self.view).reshape(4, 4, order='F')
        projection = np.asarray(self.projection).reshape(4, 4, order='F')
        clip = projection @ view @ np.r_[xyz, 1.0]
        if clip[3] <= 0:
            return None
        ndc = clip[:3] / clip[3]
        return ((ndc[0] + 1) * PANE_WIDTH/2, (1 - ndc[1]) * PANE_HEIGHT/2)

    def _render_scene(self):
        raw = p.getCameraImage(PANE_WIDTH, PANE_HEIGHT, self.view, self.projection,
            renderer=p.ER_TINY_RENDERER, shadow=1, lightDirection=[1, -1, 3],
            physicsClientId=self.task.robot.client)[2]
        picture = Image.fromarray(np.asarray(raw, dtype=np.uint8)[:, :, :3])
        draw = ImageDraw.Draw(picture)
        start = self._pixel(self.task.start)
        end = self._pixel(self.task.start + np.asarray(self.cfg['displacement']))
        if start and end:
            draw.line([start, end], fill='#00a2d8', width=4)
        actual = [self._pixel(point) for point in self.task.trace['x'][::4]]
        actual = [point for point in actual if point is not None]
        if len(actual) > 1:
            draw.line(actual, fill='#23a455', width=3)
        target = self._pixel(self.task.state['xref'])
        if target:
            x, y = target
            draw.line([(x-8, y), (x+8, y)], fill='#003f6b', width=3)
            draw.line([(x, y-8), (x, y+8)], fill='#003f6b', width=3)
        current = self._pixel(self.task.state['x'])
        if current:
            x, y = current
            draw.ellipse((x-4, y-4, x+4, y+4), fill='#23a455', outline='white', width=1)
        # Display annotation only; the sphere and robot still come from physics.
        center = self._pixel(self.cfg['obstacle']['center'])
        if center:
            cx, cy = center
            lx = min(max(cx + 45, 180), PANE_WIDTH - 165)
            ly = min(max(cy - 62, 18), PANE_HEIGHT - 95)
            draw.line([(lx, ly + 16), (cx, cy)], fill='#b51f28', width=3)
            direction = np.asarray([cx-lx, cy-(ly+16)], dtype=float)
            norm = np.linalg.norm(direction)
            if norm > 1:
                unit = direction/norm
                ortho = np.asarray([-unit[1], unit[0]])
                tip = np.asarray([cx,cy])
                draw.polygon([tuple(tip), tuple(tip-10*unit+5*ortho), tuple(tip-10*unit-5*ortho)], fill='#b51f28')
            draw.rounded_rectangle((lx-5, ly-3, lx+159, ly+29), radius=5, fill='white', outline='#b51f28', width=2)
            draw.text((lx+2, ly+2), 'Sphere obstacle', font=font(18), fill='#9e1921')
        draw.rectangle((0, PANE_HEIGHT-30, PANE_WIDTH, PANE_HEIGHT), fill='#f4f6f8')
        draw.text((12, PANE_HEIGHT-25), 'Blue: reference   Green: actual tool path', font=font(16), fill='#172b4d')
        return picture

    def image(self, display_time):
        if self.frozen is None:
            picture, state = self._render_scene(), self.task.state
        else:
            picture, state = self.frozen
        output = Image.new('RGB', (PANE_WIDTH, HEADER_HEIGHT+PANE_HEIGHT+FOOTER_HEIGHT), '#f4f6f8')
        output.paste(picture, (0, HEADER_HEIGHT))
        draw = ImageDraw.Draw(output)
        draw.text((14, 9), self.label, font=font(24), fill='#172b4d')
        obstacle_distance = state['collision']['obstacle_clearance']
        clearance = state['collision']['self_clearance']
        if obstacle_distance is not None:
            clearance = min(clearance, obstacle_distance)
        draw.text((14, 43), f"state t={state['t']:.3f}s   error={1000*state['error']:.2f}mm",
                  font=font(17), fill='#293749')
        draw.text((14, 69), f'min current clearance={1000*clearance:.2f}mm',
                  font=font(17), fill='#293749')
        footer_y = HEADER_HEIGHT + PANE_HEIGHT
        if self.frozen is not None:
            draw.rectangle((0, footer_y, PANE_WIDTH, footer_y+FOOTER_HEIGHT), fill='#922b21')
            draw.text((14, footer_y+6), f'FAIL at {self.failure_time:.3f}s — FROZEN',
                      font=font(24), fill='white')
            draw.text((14, footer_y+43), ', '.join(self.failure_reasons), font=font(16), fill='white')
        elif display_time >= self.cfg['duration'] - 1e-10:
            draw.text((14, footer_y+10), 'COMPLETE — all checks passed', font=font(22), fill='#16723b')
        else:
            draw.text((14, footer_y+10), 'RUNNING — not yet a success', font=font(20), fill='#34465d')
        return output

    def evidence(self):
        self.advance_to(self.cfg['duration'])
        summary = self.task.summary()
        if self.task.steps != len(self.commands):
            raise ValueError(f'{self.label}: incomplete physical replay')
        if summary['success'] != self.source_summary['success']:
            raise ValueError(f'{self.label}: replay changed the source success result')
        if summary['failure_reasons'] != self.source_summary['failure_reasons']:
            raise ValueError(f'{self.label}: replay changed source failure reasons')
        if not self.task.done:
            raise ValueError(f'{self.label}: source ended before a task termination')
        return dict(controller=self.label, source=str(self.directory.resolve()),
            source_config_sha256=sha256(self.directory/'config.json'),
            source_trajectory_sha256=sha256(self.directory/'trajectory.npz'),
            source_summary_sha256=sha256(self.directory/'summary.json'),
            source_success=self.source_summary['success'], physics_steps=self.task.steps,
            max_q_difference_rad=self.max_q_difference, q_tolerance_rad=REPLAY_ATOL,
            first_failure_time_s=self.failure_time, failure_reasons=summary['failure_reasons'],
            physical_stop_time_s=self.task.state['t'],
            visual_freeze_time_s=self.failure_time,
            replay_success=summary['success'], physical_replay_verified=True)


def render(evaluation, scenario, output, seed=44):
    import imageio_ffmpeg
    if output.suffix.lower() != '.mp4':
        raise ValueError('--output must be a new .mp4 file')
    metadata_path = output.with_suffix('.json')
    if output.exists() or metadata_path.exists():
        raise FileExistsError('Video/metadata already exists; choose a new experiment output')
    if Path(scenario).name != scenario:
        raise ValueError('Scenario must be an ID, not a filesystem path')
    directories = [('Tracker only', evaluation/'rollouts'/'tracker'/scenario),
                   ('Potential field', evaluation/'rollouts'/'potential'/scenario),
                   (f'PPO seed {seed}', evaluation/'rollouts'/f'ppo-seed{seed}'/scenario)]
    for _, directory in directories:
        for name in ('config.json', 'summary.json', 'trajectory.npz'):
            if not (directory/name).is_file():
                raise FileNotFoundError(directory/name)
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(output.stem+'.partial.mp4')
    if temporary.exists():
        raise FileExistsError(temporary)
    with ExitStack() as stack:
        panes = [ReplayPane(directory, label, stack) for label, directory in directories]
        if any(pane.cfg != panes[0].cfg for pane in panes[1:]):
            raise ValueError('Paired controllers do not share identical physical scenario configs')
        if panes[0].cfg['scenario_id'] != scenario:
            raise ValueError('Requested ID differs from stored scenario config')
        duration = panes[0].cfg['duration']
        frame_count = round(duration * FPS)
        if frame_count < 1 or abs(frame_count/FPS-duration) > 1e-8:
            raise ValueError('Reference duration must be a positive multiple of 1/30 s')
        top_height = 64
        height = top_height + HEADER_HEIGHT + PANE_HEIGHT + FOOTER_HEIGHT
        writer = imageio_ffmpeg.write_frames(str(temporary), (3*PANE_WIDTH, height), fps=FPS,
            codec='libx264', quality=8, macro_block_size=2, pix_fmt_in='rgb24',
            pix_fmt_out='yuv420p', ffmpeg_log_level='error')
        writer.send(None)
        try:
            for frame_index in range(frame_count):
                display_time = (frame_index+1)/FPS
                canvas = Image.new('RGB', (3*PANE_WIDTH, height), '#13283f')
                draw = ImageDraw.Draw(canvas)
                draw.text((16, 7), f'{scenario}   |   shared reference clock {display_time:.3f} / {duration:.3f} s',
                          font=font(21), fill='white')
                draw.text((16, 36), 'Physical motor-command replay | Blue: reference / target + | Green: tool trace | Video is illustrative, not batch evidence',
                          font=font(16), fill='#c8d5e2')
                for index, pane in enumerate(panes):
                    pane.advance_to(display_time)
                    canvas.paste(pane.image(display_time), (index*PANE_WIDTH, top_height))
                writer.send(np.asarray(canvas, dtype=np.uint8))
            evidence = [pane.evidence() for pane in panes]
        finally:
            writer.close()
        metadata = dict(created_utc=datetime.now(timezone.utc).isoformat(),
            source_evaluation=str(evaluation.resolve()), scenario_id=scenario,
            renderer_script_sha256=sha256(Path(__file__)),
            ppo_seed=seed, video_file=str(output.resolve()), fps=FPS, frame_count=frame_count,
            reference_duration_s=duration, video_duration_s=frame_count/FPS,
            physics_dt_s=panes[0].cfg['dt'], resolution=[3*PANE_WIDTH, height],
            physical_replay='Initial ControlTask reset only; saved per-step motor velocity commands through advance and stepSimulation.',
            temporal_sampling='Frame k samples (k+1)/fps; nearest physics time, ending at reference duration.',
            failure_display='Freeze first failed checked state; show failure time. If source continued after tracking failure, hidden physical replay continues for q verification.',
            replay_grouping='Original action-repeat groups split into individual steps for video sampling; dt, commands, motor limits and collision checks unchanged.',
            evidence_scope='Illustration of one selected scenario. Does not replace paired batch success metrics.',
            panes=evidence)
        temporary.rename(output)
        metadata['video_sha256'] = sha256(output)
        metadata_path.write_text(json.dumps(metadata, indent=2)+'\n')
    return metadata_path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--evaluation', type=Path, required=True)
    parser.add_argument('--scenario', required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--ppo-seed', type=int, default=44)
    args = parser.parse_args()
    metadata = render(args.evaluation, args.scenario, args.output, args.ppo_seed)
    print(json.dumps({'video': str(args.output.resolve()), 'metadata': str(metadata.resolve())}))


if __name__ == '__main__':
    main()
